name: ci workflow

on:
  - push
  - pull_request

jobs:
  test:
    name: test

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: ["14", "16", "18", "19"]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: test
        run: npm t

  coverage:
    name: coverage
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: install dependencies
        run: npm ci
      - name: calculate coverage
        run: npm run coverageCalculation
      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: deploy
    needs: coverage
    if: github.ref == 'refs/heads/master' && !contains(toJSON(github.event.commits.*.message), '[no-deploy]')

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: install dependencies
        run: npm ci
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

